exclude: '.project-template|docs/conf.py'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    -   id: mypy
        additional_dependencies:
        -   eth-utils>=2

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-gfm
        -   mdformat-frontmatter
        -   mdformat-pyproject
        args: ["README.md", "newsfragments/README.md"]

default_language_version:
    python: python3
