version: 2.0

# heavily inspired by:
# https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: checkout fixtures submodule
        command: git submodule update --init --recursive
    - run:
        name: merge pull request base
        command: ./.circleci/merge_pr.sh
    - run:
        name: merge pull request base (2nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - run:
        name: merge pull request base (3nd try)
        command: ./.circleci/merge_pr.sh
        when: on_fail
    - restore_cache:
        keys:
          - cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: ~/.local/bin/tox
    - save_cache:
        paths:
          - .hypothesis
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-v1-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  py35-core:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV: py35-core
  py36-core:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-core
  py37-core:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-core
  pypy3-core:
    <<: *common
    docker:
      - image: pypy:3-5.8.0
        environment:
          TOXENV: pypy3-core

  py35-doctest:
    <<: *common
    docker:
      - image: circleci/python:3.5
        environment:
          TOXENV: py35-doctest
  py36-doctest:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: py36-doctest
  py37-doctest:
    <<: *common
    docker:
      - image: circleci/python:3.7
        environment:
          TOXENV: py37-doctest
  pypy3-doctest:
    <<: *common
    docker:
      - image: pypy:3-5.8.0
        environment:
          TOXENV: pypy3-doctest

  lint:
    <<: *common
    docker:
      - image: circleci/python:3.6
        environment:
          TOXENV: lint

workflows:
  version: 2
  test:
    jobs:
      - py35-core
      - py36-core
      - py37-core
      - pypy3-core

      - py35-doctest
      - py36-doctest
      - py37-doctest
      - pypy3-doctest

      - lint
