name: Docs

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"

      - name: Build HTML Docs
        run: uv run --group docs sphinx-build -W -b html docs docs/_build/html

      - name: Run Doctests
        run: uv run --group docs sphinx-build -W -b doctest docs docs/_build/doctest
